### ISSUE TITLE
Slow Download Speed

### ISSUE THREAD

**Issue by lquitsch** [i-telligence/fs-extractor-maven-plugin#1]
First of all: Good job and thank you! 

Instead of writing every single byte use 
```java
Files.copy(is, Paths.get(filePath), StandardCopyOption.REPLACE_EXISTING);
```
instead of 
```java
FileOutputStream fos = new FileOutputStream(new File(filePath));

int inByte;
while ((inByte = is.read()) != -1) {
    fos.write(inByte);
}
```
Like this the download is mutiple times faster.

I also added the javadocs for download and deployment

I made a little change to the readme also, i'm adding my changed file here, because i couldn't make a pull request.

[FSExtractMojo.zip](https://github.com/i-telligence/fs-extractor-maven-plugin/files/2904368/FSExtractMojo.zip)
[README.zip](https://github.com/i-telligence/fs-extractor-maven-plugin/files/2904390/README.zip)

**Comment by i-telligence-af** [comment]
Thank you @lquitsch ! That change made it massively faster.
